# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

zh:
  languageCode: zh-Hans
  contentDir: content/zh
  title: 占俊飞的个人主页
  params:
    description: '占俊飞的个人网站。展示优化、人工智能和节能计算领域的研究、学术背景和项目。'
  menu:
    main:
      - name: 首页
        url: /
        weight: 10
      - name: 经历
        url: experience/
        weight: 20
      - name: 研究
        url: research/
        weight: 40
      - name: 项目
        url: projects/
        weight: 50
      - name: 写作样本
        url: samples/
        weight: 60
